### ISSUE TITLE
Library usage - Yml --> Byml

### ISSUE THREAD

**Issue by mariopossamato** [leoetlino/byml-v2#10]
Is there a way to get a byml from a yml in the python shell?

**Comment by NiceneNerd** [comment]
Check out the source for the `yml_to_byml` command to see how it works: https://github.com/zeldamods/byml-v2/blob/master/byml/yml_to_byml.py. The key lines are 20, 21, and 25.

**Comment by mariopossamato** [comment]
Thank you! :D
