### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by benwa** [leoetlino/byml-v2#11]
I've got a byaml save from Ring Fit Adventure. Looks like it's a v4 schema, but when running byml_to_yml, I don't get anything usable. Is this the expected output, or are modifications going to be required?

[20913_080119.zip](https://github.com/zeldamods/byml-v2/files/5380925/20913_080119.zip)

**Comment by NiceneNerd** [comment]
Hmm, same output with `oead` with no error in either, so that probably does represent the actual data it stores.

**Comment by leoetlino** [comment]
Yeah, looks like the game has obfuscated this BYML. The unsigned integers are most likely CRC32 hashes.

**Comment by benwa** [comment]
I was able to find a couple of values that are in the save, like coins and quantity of an item.

@leoetlino any ideas on what I can do next. Do you think this'll require some Ghidra work?

**Comment by leoetlino** [comment]
Possibly. You can also try to dump all the strings that are in the executable, compute their CRC32 hashes and use that as a dictionary to map CRC32 hashes back to human-readable strings -- assuming the relevant strings are in the executable. But that's worth testing in my opinion.
