### ISSUE TITLE
Eh... huh?

### ISSUE THREAD

**Issue by NateHevens** [leoetlino/byml-v2#12]
![Screenshot (1)](https://user-images.githubusercontent.com/36975652/98322475-7c4e9b00-1fb5-11eb-9c5f-7dda7fcf2b37.png)

So I got a couple odd errors trying to install this. BYML is extracted to my Documents folder, but AAMP didn't really have an issue with that.

I do have Python installed, of course, but in my AppData folder (where it installs by default, I guess?). It worked with AAMP so I'm wondering what's wrong, here...

**Comment by NiceneNerd** [comment]
You have 32 bit Python and need 64 bit.
