### ISSUE TITLE
keeps giving me an error from line 7

### ISSUE THREAD

**Issue by impostor5875** [leoetlino/byml-v2#13]
so, i know this thing is 100% not actively maintained anymore, and i doubt i'm gonna get a response, but i just wanted to use this so i could mess around with splatoon 2's byml files. anyways, every time i try to use it, it just says "error in line 7, you can't use 'from . import byml'" 🤓🤓🤓🤓🤓🤓🤓

i saw another issue (#9) relating to this, but all you responded with was just to "use `byml_to_yml` instead"? how exactly do you "use" a python file without opening it in command prompt? 

i won't send the image because it's just the exact same thing as in issue #9

**Comment by impostor5875** [comment]
after looking at the other issue again, i realized that person added the ".py" extension after `byml_to_yml`, but i never did that and i still got the error

**Comment by leoetlino** [comment]
Both are equivalent on Windows and equally incorrect commands. The command is just `byml_to_yml`. Don't use a path or it won't work.
