### ISSUE TITLE
im very confused

### ISSUE THREAD

**Issue by yunoluvsemogaze** [leoetlino/byml-v2#17]
hi, i'm fairly new to modding and since both the switch toolbox and ex-king editor don't support byml v7 yet, i'm trying to convert some .byml files into .yml files and see if they'll work. anyways, im confused as how to use this. idrk if it's right but the exact command i type in is as follows:

byml_to_yml C:/Users/User/Downloads/mwf/Weapon_Sword_070.Nin_NX_NVN.esetb.byml !!.yml

and it gives me the error :

"Fatal error in launcher: Unable to create process using '"C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe"  "C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\byml_to_yml.exe" C:/Users/User/Downloads/mwf/Weapon_Sword_070.Nin_NX_NVN.esetb.byml !!.yml': The system cannot find the file specified."

i would love to know more about what i'm doing wrong. thank you as always !!

**Comment by leoetlino** [comment]
Have you installed byml-v2?

Also, note that we don't fully support v7 either at the moment. You might get some errors if the file you're trying to convert uses new, unsupported node types.

**Comment by yunoluvsemogaze** [comment]
> 

yes, i'm using the latest version of the converter. i'm just curious if the command / prompt i wrote was right or not. somehow, the script wasn't installed so i manually installed it. it seemed to have done something but it gives me another error instead:

"File "C:\Program Files\Python311\Scripts\byml_to_yml.py", line 7, in <module>
   from . import byml
ImportError: attempted relative import with no known parent package"

would love to know if i'm writing the commands right or not. thanks !!

**Comment by leoetlino** [comment]
The manual install is wrong, but your first command should have worked.

Unfortunately, I have no idea why it's not working as I'm not a Windows user. Can you post the output of `pip install byml`?

**Comment by yunoluvsemogaze** [comment]
here's how it looks like:


![image](https://github.com/zeldamods/byml-v2/assets/133940708/fe6bae17-ee30-4486-9b72-76d1cb11e4d5)

**Comment by leoetlino** [comment]
Sounds like your Python install is messed up - notice how pip says it's installed to your Python 3.11 install, but when you try to run `byml_to_yml`, the Python launcher is trying to use Python 3.10.

I'd suggest uninstalling 3.10 and reinstalling 3.11. This is not a problem with byml-v2 itself so I'm closing this issue.

**Comment by yunoluvsemogaze** [comment]
okay will do, thank you !!
