### ISSUE TITLE
No such directory "wszst"

### ISSUE THREAD

**Issue by Arudarin** [leoetlino/byml-v2#2]
Hey, I'm trying to edit a .sbyml file for BOTW, and I get this log whenever I try to convert it into a .yml:

```
>>byml_to_yml ActorInfo.product.sbyml Actor.yml
Traceback (most recent call last):
  File "/usr/local/bin/byml_to_yml", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/byml/byml_to_yml.py", line 25, in main
    data = wszst_yaz0.decompress(data)
  File "/usr/local/lib/python3.6/dist-packages/wszst_yaz0/__init__.py", line 26, in decompress
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wszst': 'wszst'
```

I tried to install wszst manually, but it seems it is already installed.
```
>>pip3 install wszst_yaz0
Requirement already satisfied: wszst_yaz0 in /usr/local/lib/python3.6/dist-packages
```

**Comment by leoetlino** [comment]
wszst_yaz0 is only a wrapper module -- you need to install wszst manually on Linux: https://szs.wiimm.de/download.html#vers

Maybe I should ship the wszst binary for Linux too?...

**Comment by Arudarin** [comment]
I feel that would be for the best. Or at least have a mention in the README of the requirement. I'm typing this on mobile right now, I'll let you know how everything goes once I get my hands on my desktop again.

**Comment by Arudarin** [comment]
Alright! Managed to install SZS, got a new error.

```
>>byml_to_yml ActorInfo.product.sbyml Actor.yml
Traceback (most recent call last):
  File "/usr/local/bin/byml_to_yml", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/byml/byml_to_yml.py", line 21, in main
    file = sys.stdin.buffer if args.byml == '-' else open(args.byml, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'ActorInfo.product.sbyml'
```

**Comment by leoetlino** [comment]
Yeah the README should probably mention wszst is needed (to read and write compressed files). Unfortunately I don't have a lot of time right now, so a PR would be really appreciated ;-)

Are you sure there's an ActorInfo.product.sbyml file in your current working directory?

**Comment by leoetlino** [comment]
byml-v2 doesn't use wszst anymore: https://github.com/zeldamods/byml-v2/commit/cb220963afaf45033f2ee3250eaefe6360087466 (this has been the case since Dec 2019)

Nowadays, oead is used for Yaz0 compression/decompression, and binary builds are provided for Windows, Linux and macOS (64-bit)
