### ISSUE TITLE
Can't decode cp1252 strings

### ISSUE THREAD

**Issue by NiceneNerd** [leoetlino/byml-v2#4]
Turns out Ice Spear doesn't necessarily use UTF-8, and `byml` will fail to parse `cp1252` encoded strings. 'Twould be easy enough to support either.

**Comment by leoetlino** [comment]
Nintendo doesn't use CP1252 for BYML as far as I know, and this only masks a `byaml-lib` bug in Ice Spear that was fixed several months ago: https://gitlab.com/ice-spear-tools/byaml-lib/commit/0dae2d16cf87adf3fcfe13a2455a4599b75a7858
