### ISSUE TITLE
error command  def main() -> None:

### ISSUE THREAD

**Issue by ImanCol** [leoetlino/byml-v2#8]
![image](https://user-images.githubusercontent.com/26169049/94831472-60fad980-03d2-11eb-88c8-04ca4106886e.png)

**Comment by NiceneNerd** [comment]
What version of Python do you have?

**Comment by ImanCol** [comment]
I have several versions. But it was somehow fixed if I launch "byml_to_yml" from the "python/script" folder. I managed to decrypt.

But when re-encrypting with "yml_to_byml", I get the following error.

![image](https://user-images.githubusercontent.com/26169049/94839227-52192480-03dc-11eb-93af-cf46d09e316b.png)

**Comment by NiceneNerd** [comment]
One note: it's not encrypting anything.

Anyway, the problem is you're trying to use the `yml_to_byml` command but gave it the `.byml` file as the first argument. It's trying to parse the original BYML file as YAML.

**Comment by ImanCol** [comment]
Yes, the mistake was mine. Although I had to add the quotes in the path because I got another error. Thanks for this great tool.
![image](https://user-images.githubusercontent.com/26169049/94840023-6b6ea080-03dd-11eb-9081-a994f8b3cb38.png)

**Comment by NiceneNerd** [comment]
I didn't make it; I've just probably used it more than anyone else.

**Comment by ImanCol** [comment]
There are other types of files that I would like to decrypt, although I don't know if they are also YAML format, as they have other types of formats such as ".alsarc", ".bslnk", ".sarc", ".blarc", etc ...for SM3DAS

But at least this tool covers what is necessary. Thank you.

**Comment by NiceneNerd** [comment]
Again, it's [not encryption or decryption](https://www.google.com/search?q=define+encrypt).

But the tool you want for those files is [`sarc`](https://github.com/zeldamods/sarc)

**Comment by ImanCol** [comment]
I have been trying other .byml files but with failed results. Hope this tool expands to the SM3DAS game

![image](https://user-images.githubusercontent.com/26169049/94851235-cc05d980-03ed-11eb-99db-680423680124.png)
